CREATE DATABASE MUSIC_RECSYS;

-- SONG METADATA TABLE
CREATE TABLE SONG_INFO(
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    SONG_ID VARCHAR(100) UNIQUE NOT NULL,
    SONG_NAME VARCHAR(255) NOT NULL,
    SPOTIFY_ID VARCHAR(100) UNIQUE NOT NULL,
    SONG_ART TEXT,
    ARTIST_NAMES TEXT NOT NULL,
    RELEASE_DATE DATE,
    DANCEABILITY DOUBLE DEFAULT 0,
    ENERGY DOUBLE DEFAULT 0,
    KEY DOUBLE DEFAULT 0,
    LOUDNESS DOUBLE DEFAULT 0,
    MODE DOUBLE DEFAULT 0,
    SPEECHINESS DOUBLE DEFAULT 0,
    ACOUSTICNESS DOUBLE DEFAULT 0,
    INSTRUMENTALNESS DOUBLE DEFAULT 0,
    LIVENESS DOUBLE DEFAULT 0,
    VALENCE DOUBLE DEFAULT 0,
    TEMPO DOUBLE DEFAULT 0,
    EMBEDDINGS TEXT
);


-- USER METADATA TABLE
CREATE TABLE USER_INFO(
    IDX INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(50) UNIQUE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    NEXT_GEN_REC DATE,
    FAV_ARTISTS TEXT
);

-- USER SONG DATA
CREATE TABLE USER_HISTORY(
    USR_IDX INTEGER REFERENCES USER_INFO(IDX) ON DELETE CASCADE,
    SONG_IDX INTEGER REFERENCES SONG_INFO(IDX) ON DELETE CASCADE,
    LAST_LISTNED_MS NUMERIC, 
    PRIMARY KEY(USR_IDX,SONG_IDX)
);

--
CREATE TABLE SONG_SONG_SIMS(
    IDX_1 INTEGER REFERENCES SONG_INFO(IDX) ON DELETE CASCADE,
    IDX_2 INTEGER REFERENCES SONG_INFO(IDX) ON DELETE CASCADE,
    SIM NUMERIC(10,9) NOT NULL,
    UNIQUE(IDX_1,IDX_2)
);


-- Index
--      -- SONG_INFO
CREATE INDEX SONG_ID_INDX ON SONG_INFO(SONG_ID);
CREATE INDEX SONG_NAME_INDX ON SONG_INFO(SONG_NAME);
CREATE INDEX ARTIST_NAMES_INDX ON SONG_INFO(ARTIST_NAMES);

--      -- SONG_SONG_SIMS
CREATE INDEX IDX_1_INDX ON SONG_SONG_SIMS(IDX_1);
CREATE INDEX IDX_2_INDX ON SONG_SONG_SIMS(IDX_2);

--      -- USER_INFO
CREATE INDEX USERNAME_INDX ON USER_INFO(USERNAME);



-- Sample Input
INSERT INTO SONG_INFO (SONG_ID,SONG_NAME,SPOTIFY_ID,SONG_ART,ARTIST_NAMES,RELEASE_DATE,DANCEABILITY,ENERGY,KEY,LOUDNESS,MODE,SPEECHINESS,ACOUSTICNESS,INSTRUMENTALNESS,LIVENESS,VALENCE,TEMPO,EMBEDDINGS) VALUES ('ABCFGGHJB','First Thing','1XtR5oQsad0JY5dJakjGOL','{}','Four Tet','2003-03-05',0.229000,0.011600,7.000000,-34.229000,1.000000,0.035800,0.940000,0.752000,0.049100,0.039100,80.441000,"1,2,3,4");