\c postgres;
DROP DATABASE MUSIC_RECSYS;

CREATE DATABASE MUSIC_RECSYS;
\c music_recsys;

-- SONG METADATA TABLE
CREATE TABLE SONG_INFO(
    SONG_ID VARCHAR(100) PRIMARY KEY,
    SONG_NAME VARCHAR(255) NOT NULL,
    SPOTIFY_ID VARCHAR(100) UNIQUE NOT NULL,
    SONG_ART TEXT,
    ARTIST_NAMES TEXT NOT NULL,
    RELEASE_YEAR INTEGER,
    DANCEABILITY DECIMAL DEFAULT 0,
    ENERGY DECIMAL DEFAULT 0,
    KEY DECIMAL DEFAULT 0,
    LOUDNESS DECIMAL DEFAULT 0,
    MODE DECIMAL DEFAULT 0,
    SPEECHINESS DECIMAL DEFAULT 0,
    ACOUSTICNESS DECIMAL DEFAULT 0,
    INSTRUMENTALNESS DECIMAL DEFAULT 0,
    LIVENESS DECIMAL DEFAULT 0,
    VALENCE DECIMAL DEFAULT 0,
    TEMPO DECIMAL DEFAULT 0
);


-- USER METADATA TABLE
CREATE TABLE USER_INFO(
    USERNAME VARCHAR(50) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    NEXT_GEN_REC DATE,
    FAV_ARTISTS TEXT
);

-- USER SONG DATA
CREATE TABLE USER_HISTORY(
    USR_IDX VARCHAR(100) REFERENCES USER_INFO(USERNAME) ON DELETE CASCADE,
    SONG_ID VARCHAR(100) REFERENCES SONG_INFO(SONG_ID) ON DELETE CASCADE,
    LAST_LISTNED_MS NUMERIC, 
    PRIMARY KEY(USR_IDX,SONG_ID)
);

--
CREATE TABLE SONG_SONG_SIMS(
    ID_1 VARCHAR(100) REFERENCES SONG_INFO(SONG_ID) ON DELETE CASCADE,
    ID_2 VARCHAR(100) REFERENCES SONG_INFO(SONG_ID) ON DELETE CASCADE,
    SIM NUMERIC(10,9) NOT NULL,
    UNIQUE(ID_1,ID_2)
);


-- Index
--      -- SONG_INFO
CREATE INDEX SONG_ID_INDX ON SONG_INFO(SONG_ID);
CREATE INDEX SONG_NAME_INDX ON SONG_INFO(SONG_NAME);
CREATE INDEX ARTIST_NAMES_INDX ON SONG_INFO(ARTIST_NAMES);

--      -- SONG_SONG_SIMS
CREATE INDEX ID_1_INDX ON SONG_SONG_SIMS(ID_1);
CREATE INDEX ID_2_INDX ON SONG_SONG_SIMS(ID_2);

--      -- USER_INFO
CREATE INDEX USERNAME_INDX ON USER_INFO(USERNAME);



-- Sample Input
INSERT INTO SONG_INFO (SONG_ID,SONG_NAME,SPOTIFY_ID,SONG_ART,ARTIST_NAMES,RELEASE_DATE,DANCEABILITY,ENERGY,KEY,LOUDNESS,MODE,SPEECHINESS,ACOUSTICNESS,INSTRUMENTALNESS,LIVENESS,VALENCE,TEMPO) VALUES ('ABCFGGHJB','First Thing','1XtR5oQsad0JY5dJakjGOL','{}','Four Tet','2003-03-05',0.229000,0.011600,7.000000,-34.229000,1.000000,0.035800,0.940000,0.752000,0.049100,0.039100,80.441000);